Drop deprecated API usage in HVAC
StackStorm-Exchange/stackstorm-vault pull request #17
Opened 2021-01-16 02:53 UTC by cognifloyd

#14 adjusts requirements to use `hvac>=0.10.6`, which is the latest.
hvac has had significant refactoring, moving the python API to new
locations. We do not need to keep anything that is deprecated.

2021-01-16 15:24 UTC, nmaludy requested changes
Would be nice if there were unit tests to run the code and ensure that it works.

2021-01-16 15:25 UTC, nmaludy commented
@cognifloyd also would be nice to get a CHANGELOG update with all of the changes you've made, please.

Thanks for the work on this!

2021-01-19 15:35 UTC, cognifloyd commented
I'll write the tests in a different PR. Once they pass, we can merge them, and then rebase this so that they run with the modified code. Thus, we'll have before and after tests.

2021-02-04 04:30 UTC, cognifloyd commented
OK. The unit tests passed on master without this migration. Now they are passing with this migration. I had to adjust two tests where the new methods are actually returning something where the old ones didn't.

I also bumped the version to 0.6.0 and added bullet points to CHANGES.md

I am keeping 2 in python_versions here, because I need to use this on st2 instances with python2. I'll drop the 2 when we are ready to drop it across the exchange.

2021-02-04 06:35 UTC, blag approved these changes

2021-02-04 06:35 UTC, merged